const ROOT_URL =
  process.env.NEXT_PUBLIC_URL ||
  (process.env.VERCEL_URL && `https://${process.env.VERCEL_URL}`) ||
  "http://localhost:3000";

/**
 * MiniApp configuration object. Must follow the mini app manifest specification.
 *
 * @see {@link https://docs.base.org/mini-apps/features/manifest}
 */
export const minikitConfig = {

  accountAssociation: {
    header: "eyJmaWQiOjEzMzI0NTgsInR5cGUiOm51bGwsImtleSI6IjB4ODg1MDA2NzhmNDJlZjUxNzE0ZDc1MWNBRjZFMTQwZjU4ODQwNjNhQSJ9",
    payload: "eyJkb21haW4iOiJtaS1wcmltZXJhLW1pbmktYXBwLWlvdGEudmVyY2VsLmFwcCJ9",
    signature: "MHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjYwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwYzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMTIwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAxNzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDE4ZTc4YzAzOWJhYmY0NWEwMDJiMDg3MzEwMzRlM2NkNmM1ZGM5ZjliNWU4NjZmZTJiZjlhMWJkNWQ5ZGYyOTVjMzk0ZDQ1ZDkwZTdmNzhmODY2YTNmM2VlNGJmYjYxNjFhOGI5ZWQwZTFmY2ViMzQyOTAyMTE5NGQ0YjcyOTVkMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjVmMTk4MDg2YjJkYjE3MjU2NzMxYmM0NTY2NzNiOTZiY2VmMjNmNTFkMWZiYWNkZDdjNDM3OWVmNjU0NjU1NzJmMWQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjc3YjIyNzQ3OTcwNjUyMjNhMjI3NzY1NjI2MTc1NzQ2ODZlMmU2NzY1NzQyMjJjMjI2MzY4NjE2YzZjNjU2ZTY3NjUyMjNhMjI3NDZkNTM2YjU5NzQ0MjQ4NmQzNjc1NmY3NDYxNjYzMDUxNmI3MzUxNTE1MjM2NmQ0ODc1MzI3MjY2NzU0ODM5Njc1YTUzNDgzNDZkNGY0OTdhNzg0ZDIyMmMyMjZmNzI2OTY3Njk2ZTIyM2EyMjY4NzQ3NDcwNzMzYTJmMmY2YjY1Nzk3MzJlNjM2ZjY5NmU2MjYxNzM2NTJlNjM2ZjZkMjIyYzIyNjM3MjZmNzM3MzRmNzI2OTY3Njk2ZTIyM2E2NjYxNmM3MzY1MmMyMjZmNzQ2ODY1NzI1ZjZiNjU3OTczNWY2MzYxNmU1ZjYyNjU1ZjYxNjQ2NDY1NjQ1ZjY4NjU3MjY1MjIzYTIyNjQ2ZjIwNmU2Zjc0MjA2MzZmNmQ3MDYxNzI2NTIwNjM2YzY5NjU2ZTc0NDQ2MTc0NjE0YTUzNGY0ZTIwNjE2NzYxNjk2ZTczNzQyMDYxMjA3NDY1NmQ3MDZjNjE3NDY1MmUyMDUzNjU2NTIwNjg3NDc0NzA3MzNhMmYyZjY3NmY2ZjJlNjc2YzJmNzk2MTYyNTA2NTc4MjI3ZDAwMDAwMDAwMDAwMDAwMDAwMA"
  },
  baseBuilder: {
    allowedAddresses: ["0x88500678f42ef51714d751cAF6E140f5884063aA"],
  },
  miniapp: {
    version: "1",
    name: "miPrimeraMiniApp",
    subtitle: "",
    description: "",
    screenshotUrls: [],
    iconUrl: `${ROOT_URL}/icon.png`,
    splashImageUrl: `${ROOT_URL}/splash.png`,
    splashBackgroundColor: "#000000",
    homeUrl: ROOT_URL,
    webhookUrl: `${ROOT_URL}/api/webhook`,
    primaryCategory: "utility",
    tags: ["example"],
    heroImageUrl: `${ROOT_URL}/hero.png`,
    tagline: "",
    ogTitle: "",
    ogDescription: "",
    ogImageUrl: `${ROOT_URL}/hero.png`,
  },
} as const;
